spring.application.name=SpringMVC

jwt.secret = H2m5LJx5G8z7dVQv7uL4Q1W0W2YgL7Xk2j0Q6cA0b5M=
jwt.access-expiration = 30000
jwt.refresh-expiration = 120000

spring.datasource.url=jdbc:h2:file:./data/jwtdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=true

